name: Get OIDC Token
on: 
    workflow_dispatch: # manually trigger
permissions:
  id-token: write
  contents: read

jobs:
  get-oidc-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token
        id: get_token
        run: |
          echo "TOKEN=$(curl -H \"Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN\" \"$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com\")" >> $GITHUB_ENV
      - name: Print OIDC Token
        run: echo "OIDC Token: ${{ env.TOKEN }}"
