name: 2ndTestProject
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        # second_action folder working directory.
        working-directory: second_action
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.7
        
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            second_action:
              - 'second_action/**'

      - name: Install NodeJS
        if: steps.filter.outputs.second_action == 'true'
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install dependencies
        if: steps.filter.outputs.second_action == 'true'
        run: npm ci
        
      - name: Run tests
        if: steps.filter.outputs.second_action == 'true'
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Get Code
          uses: actions/checkout@v4.1.7
        - name: Install NodeJS
          if: steps.filter.outputs.second_action == 'true'
          uses: actions/setup-node@v4.0.2
          with:
            node-version: 20
        - name: Install dependencies
          if: steps.filter.outputs.second_action == 'true'
          run: npm ci
        - name: Build Project
          if: steps.filter.outputs.second_action == 'true'
          run: npm run build
        - name: Deploy
          if: steps.filter.outputs.second_action == 'true'
          run: echo "Deploying..."

