name: Pull Secret from AWS Secrets Manager

on: 
  workflow_dispatch: # manually trigger


permissions:
  id-token: write
  contents: read

jobs:
  pull-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials from OpenID Connect
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-session

      - name: Pull secret from AWS Secrets Manager
        id: pull_secret
        run: |
          secret=$(aws secretsmanager get-secret-value --secret-id mySecret --query 'SecretString' --output text)
          echo "secret=$secret" >> $GITHUB_ENV

      - name: Use secret
        run: echo "The secret is ${{ env.secret }}"
