name: Pull Secret from AWS Secrets Manager

on: 
  workflow_dispatch: # manually trigger

permissions:
  id-token: write
  contents: read

jobs:
  pull-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from OpenID Connect
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::766537220951:role/GithubActionsTest
          aws-region: ca-central-1 # replace with your AWS region, e.g., us-east-1

      - name: Pull secret from AWS Secrets Manager
        id: pull_secret
        run: |
          secret=$(aws secretsmanager get-secret-value --secret-id mySecret --query 'SecretString' --output text)
          echo "secret=$secret" >> $GITHUB_ENV

      - name: Use secret
        run: echo "The secret is ${{ env.secret }}"

name: Get OIDC Token

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  get-oidc-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token
        id: get_token
        run: |
          echo "TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")" >> $GITHUB_ENV
      - name: Print OIDC Token
        run: echo "OIDC Token: ${{ env.TOKEN }}"

