name: tfsec
on:
  push:
    branches:
      - main
  pull_request:

  # Add the permissions block here
permissions:
    actions: read
    contents: read
    security-events: write
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    defaults:
        run:
          # second_action folder working directory.
          working-directory: terraform
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with: 
            working_directory: terraform
            soft_fail: true
            format: sarif
            sarif_file: /terraform/tfsectest.sarif

      - name: List directory contents
        run: |
            echo "Current directory:"
            pwd
            echo "\nContents of current directory (ls):"
            ls -R
            echo "\nDirectory structure (tree):"
            sudo apt-get install tree -y
            tree
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: /terraform/tfsectest.sarif
            

